"""Shared constants for the trusted compute control plane."""

TRAIT_BOOT_TRUSTED = "CUSTOM_KEYLIME_BOOT_TRUSTED"
TRAIT_RUNTIME_TRUSTED = "CUSTOM_KEYLIME_RUNTIME_TRUSTED"
TRAIT_TRUSTED = "CUSTOM_KEYLIME_TRUSTED"
TRAIT_LEGACY_ATTESTED = "CUSTOM_KEYLIME_ATTESTED"

DEFAULT_TRUST_TRAITS = [
    TRAIT_BOOT_TRUSTED,
    TRAIT_RUNTIME_TRUSTED,
    TRAIT_TRUSTED,
    TRAIT_LEGACY_ATTESTED,
]

POLICY_MEASURED_BOOT = "measured_boot"
POLICY_IMA_RUNTIME = "ima_runtime"
POLICY_TPCM_DYNAMIC_MEASUREMENT = "tpcm_dynamic_measurement"
POLICY_EVM = "evm"

SUPPORTED_POLICY_TYPES = {
    POLICY_MEASURED_BOOT,
    POLICY_IMA_RUNTIME,
    POLICY_TPCM_DYNAMIC_MEASUREMENT,
}

LEGACY_POLICY_TYPE_ALIASES = {
    "boot": POLICY_MEASURED_BOOT,
    "tpm_pcr": POLICY_MEASURED_BOOT,
    "runtime": POLICY_IMA_RUNTIME,
    "dynamic": POLICY_TPCM_DYNAMIC_MEASUREMENT,
    "dynamic_measurement": POLICY_TPCM_DYNAMIC_MEASUREMENT,
    "tpcm_dynamic": POLICY_TPCM_DYNAMIC_MEASUREMENT,
    "opentcsm_dynamic": POLICY_TPCM_DYNAMIC_MEASUREMENT,
}

BINDING_HARDWARE_PROFILE = "hardware_profile"
BINDING_NODE = "node"

POLICY_DEPLOY_QUEUED = "queued"
POLICY_DEPLOY_NOT_DEPLOYED = "not_deployed"
POLICY_DEPLOY_APPLYING = "applying"
POLICY_DEPLOY_APPLIED = "applied"
POLICY_DEPLOY_AWAITING_REBOOT = "awaiting_reboot"
POLICY_DEPLOY_FAILED = "failed"
POLICY_DEPLOY_SUPERSEDED = "superseded"
POLICY_DEPLOY_EXTERNAL_PENDING = "external_pending"

PROVIDER_KEYLIME = "keylime"
PROVIDER_OPENTCSM = "opentcsm"
PROVIDER_DIM = "dim"

TRUST_AGENT_KEYLIME = "keylime"
TRUST_AGENT_OPENTCSM_TPCM = "opentcsm_tpcm"
TRUST_AGENT_UNMANAGED = "unmanaged"

TRUST_ROOT_TPM = "tpm"
TRUST_ROOT_TPCM = "tpcm"
TRUST_ROOT_UNKNOWN = "unknown"

TASK_PENDING = "pending"
TASK_RUNNING = "running"
TASK_SUCCESS = "success"
TASK_FAILED = "failed"
TASK_SKIPPED = "skipped"
