"""Shared constants for the trusted compute control plane."""

TRAIT_BOOT_TRUSTED = "CUSTOM_KEYLIME_BOOT_TRUSTED"
TRAIT_RUNTIME_TRUSTED = "CUSTOM_KEYLIME_RUNTIME_TRUSTED"
TRAIT_TRUSTED = "CUSTOM_KEYLIME_TRUSTED"
TRAIT_LEGACY_ATTESTED = "CUSTOM_KEYLIME_ATTESTED"

DEFAULT_TRUST_TRAITS = [
    TRAIT_BOOT_TRUSTED,
    TRAIT_RUNTIME_TRUSTED,
    TRAIT_TRUSTED,
    TRAIT_LEGACY_ATTESTED,
]

POLICY_BOOT = "boot"
POLICY_RUNTIME = "runtime"
POLICY_EVM = "evm"

BINDING_HARDWARE_PROFILE = "hardware_profile"
BINDING_NODE = "node"

PROVIDER_KEYLIME = "keylime"
PROVIDER_DIM = "dim"

TASK_PENDING = "pending"
TASK_RUNNING = "running"
TASK_SUCCESS = "success"
TASK_FAILED = "failed"
TASK_SKIPPED = "skipped"
